services:
  - type: web
    name: tow-now
    runtime: python          
    plan: free             

    buildCommand: |
      pip install -r requirements.txt   

    preDeployCommand: flask db upgrade  

    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app

    envVars:
      - key: PYTHON_VERSION            
        value: "3.10"
      - key: SECRET_KEY               
        sync: false
      # DATABASE_URL la creará Render al vincular tu Postgres
